### PR TITLE
RS: clarify file for checksig command

### PR DESCRIPTION
**Pull request by mich-elle-luna**
#DOC-1622 make the filename clear for the rpm --checksig command step

### CODE REVIEW

**Review by dwdougherty — COMMENTED** [review]
LGTM, but I'll leave it to @rrelledge to approve, as there may be another convention at play here.

I'd usually write something like: /path-to/<package.rpm>.

**Comment by rrelledge** [comment]
I agree with @dwdougherty's suggestion to make it clear that you also need to provide the filepath.
I also think it would make sense to make similar changes for `dpkg-sig --verify <path to installation package>` under step 2 of "For Ubuntu".

**Comment by mich-elle-luna** [comment]
Thank you, updated

**Review by rrelledge — APPROVED** [review]
Thank you! Looks good to me.

**Pull request merged**
