### PR TITLE
chore: add observability section

### PR DESCRIPTION
**Pull request by vmihailenco**
This was briefly discussed with @mortensi , but let me know what changes you would like to see.

### CODE REVIEW

**Review by andy-stark-redis — APPROVED** [review]
The text looks fine but I don't know enough to review the technical info.

**Comment by dwdougherty** [comment]
@mortensi Will you please take a look at this PR and comment as to its technical correctness?

**Comment by mortensi** [comment]
The sample is ok, and does not produce errors. However, the user needs a direction to effectively set up the integration.

Please, in this phase, link the full example here

https://github.com/redis/redis-py/tree/master/docs/examples/opentelemetry

When the docs will be restructured and Observability discussed on a separate, dedicated page, integrate the full example in the docs.

**Comment by mortensi** [comment]
Maybe in this phase it's possible to point the user to the full example here

https://github.com/redis/go-redis/blob/master/example/otel/README.md

Once the docs are restructured, the full example could be taken to a separate, dedicated "Observability" page.

**Comment by vmihailenco** [comment]
@mortensi I've followed your suggestion and added a link to the GitHub example. Please take another look.

**Pull request merged**
