### PR TITLE
Add CAPI viewer role

### PR DESCRIPTION
**Pull request by joniredis**
@cmilesb suggestion to add viewer (read-only) role support to the cloud API.

### CODE REVIEW

**Review by cmilesb — APPROVED** [review]
Thanks, @joniredis - Looks good to me. Could you sign the CLA (see comment from CLAassistant, above)?

**Review by andy-stark-redis — APPROVED** [review]
LGTM

**Comment by joniredis** [comment]
@cmilesb are you aware of any other places that should be updated? Sometime soon we will also release a `logs viewer` role for API that only allow such users to read the service logs through the API. That role will be good to assign to service that ingest logs to a logs repo (e.g. Splunk, Elastic, etc). We'll need to update the docs to reflect those as well by then.

**Comment by cmilesb** [comment]
@joniredis I don't think there are other places that need to be changed for this specifically. When we do add the logs viewer role, I'll have to change this and maybe some of the examples? I have a bunch of tickets to add, which roles can do what actions for both the API and for database management on the UI. The automatic CAPI docs may also help with this, which Paolo and I will be working on next quarter.

**Pull request merged**
