### PR TITLE
DEV: fix Lua API right-side nav

### PR DESCRIPTION
**Pull request by dwdougherty**
[DOC-4343](https://redislabs.atlassian.net/browse/DOC-4343)

Nav was using `<a.../a>` anchors instead of {#...}, causing the right-side nav to bug out.

[DOC-4343]: https://redislabs.atlassian.net/browse/DOC-4343?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by mich-elle-luna** [comment]
thank you! for some reason (maybe the relref in a heading?) the ### Using [`SELECT`]({{< relref "/commands/select" >}}) inside scripts is still wonky if you can fix that one as well?

**Review by mich-elle-luna — CHANGES_REQUESTED** [review]
### Using [`SELECT`]({{< relref "/commands/select" >}}) inside scripts is still weird

**Comment by dwdougherty** [comment]
Thanks, @mich-elle-luna ! I didn't catch that. Should be fixed now.

**Review by mich-elle-luna — APPROVED** [review]
thank you!

**Pull request merged**
