### PR TITLE
Update scheme name from rediss to redis

### PR DESCRIPTION
**Pull request by franklynjr**

### CODE REVIEW

**Comment by dwdougherty** [comment]
Are you sure about his, @franklynjr ? I still see plenty of references to rediss when I search for it.

**Comment by franklynjr** [comment]
> Are you sure about his, @franklynjr ? I still see plenty of references to rediss when I search for it.

this looks like a typo since the scheme portion of the URI mentioned above was `redis://LJenkins:p%40ssw0rd@redis-16379.hosted.com:16379/0`

**Comment by dwdougherty** [comment]
Okay... I'll take a closer look.

**Comment by franklynjr** [comment]
@dwdougherty actually, the above URI was not referring to TLS. It is correct. I will close.

**Comment by franklynjr** [comment]
Doc is correct. TLS connections use `rediss` schema

**Pull request closed without merging**
