### PR TITLE
Use redoc for redis cloud api reference

### PR DESCRIPTION
**Pull request by paoloredis**

### CODE REVIEW

**Comment by paoloredis** [comment]
I updated the width of the panel on the right following feedback from @dwdougherty

**Comment by cmilesb** [comment]
When you scroll to the right, the "API Docs with Redocly" button moves. Is there an option that sticks that button to the sidebar?

**Comment by paoloredis** [comment]
> When you scroll to the right, the "API Docs with Redocly" button moves on my screen. Is there an option that sticks that button to the sidebar?

I've changed the configuration so that now horizontal scrolling for the window no longer occurs.

**Comment by paoloredis** [comment]
> When you scroll to the right, the "API Docs with Redocly" button moves on my screen. Is there an option that sticks that button to the sidebar?

That's been fixed now

**Comment by mich-elle-luna** [comment]
this is looking great!

**Review by NoamSternRedis — APPROVED** [review]

**Review by cmilesb — APPROVED** [review]
It looks great! I'd like to hold off on publishing for a bit, just to give the other PMs a chance to take a look. Thanks for doing this, @paoloredis!

**Pull request merged**
